
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int LT = 23;
  public static final int ELSE = 16;
  public static final int PLUS = 2;
  public static final int INT = 19;
  public static final int RPAREN = 7;
  public static final int WHILE = 17;
  public static final int SEMI = 10;
  public static final int RCURLY = 9;
  public static final int RETURN = 18;
  public static final int IF = 15;
  public static final int GT = 25;
  public static final int LPAREN = 6;
  public static final int LE = 24;
  public static final int ID = 14;
  public static final int INT_CONST = 12;
  public static final int ATRIBUICAO = 27;
  public static final int LCURLY = 8;
  public static final int COMMA = 11;
  public static final int FLOAT = 20;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int GE = 26;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int FLOAT_CONST = 13;
  public static final int EQ = 21;
  public static final int NEQ = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "SEMI",
  "COMMA",
  "INT_CONST",
  "FLOAT_CONST",
  "ID",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "INT",
  "FLOAT",
  "EQ",
  "NEQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "ATRIBUICAO"
  };
}

